-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 18:48:11 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plantgamedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plantgamedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plantgamedb` DEFAULT CHARACTER SET utf8 ;
USE `plantgamedb` ;

-- -----------------------------------------------------
-- Table `plantgamedb`.`PlantType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`PlantType` (
  `id_plantType` INT NOT NULL AUTO_INCREMENT,
  `typeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_plantType`),
  UNIQUE INDEX `typeId_UNIQUE` (`id_plantType` ASC),
  UNIQUE INDEX `typeName_UNIQUE` (`typeName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`PlantList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`PlantList` (
  `id_Plant` INT NOT NULL AUTO_INCREMENT,
  `plantName` VARCHAR(45) NULL,
  `fk_plantType_PlLi` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_Plant`),
  UNIQUE INDEX `idPlant_UNIQUE` (`id_Plant` ASC),
  INDEX `fkPlantType_idx` (`fk_plantType_PlLi` ASC),
  CONSTRAINT `fk_plantType_PlLi`
    FOREIGN KEY (`fk_plantType_PlLi`)
    REFERENCES `plantgamedb`.`PlantType` (`id_plantType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`PlantResReference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`PlantResReference` (
  `id_resource` INT NOT NULL AUTO_INCREMENT,
  `resourceName` VARCHAR(45) NULL,
  `resVal` INT NOT NULL,
  PRIMARY KEY (`id_resource`),
  UNIQUE INDEX `resourceName_UNIQUE` (`resourceName` ASC),
  UNIQUE INDEX `idResource_UNIQUE` (`id_resource` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`PlantTypeResMod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`PlantTypeResMod` (
  `id_plantTypeResMod` INT NOT NULL AUTO_INCREMENT,
  `fk_plantType_PTRM` INT NOT NULL,
  `fk_resource_PTRM` INT NOT NULL,
  `modVal` DECIMAL(4,1) NOT NULL,
  PRIMARY KEY (`id_plantTypeResMod`),
  INDEX `fkResource_idx` (`fk_resource_PTRM` ASC),
  INDEX `fk_plantType_PTRM_idx` (`fk_plantType_PTRM` ASC),
  CONSTRAINT `fk_plantType_PTRM`
    FOREIGN KEY (`fk_plantType_PTRM`)
    REFERENCES `plantgamedb`.`PlantType` (`id_plantType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_PTRM`
    FOREIGN KEY (`fk_resource_PTRM`)
    REFERENCES `plantgamedb`.`PlantResReference` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`Player` (
  `id_player` INT NOT NULL AUTO_INCREMENT,
  `playerName` VARCHAR(45) NULL,
  PRIMARY KEY (`id_player`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`GameInstance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`GameInstance` (
  `idGameInstance` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(45) NULL,
  UNIQUE INDEX `idGameInstance_UNIQUE` (`idGameInstance` ASC),
  PRIMARY KEY (`idGameInstance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`Scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`Scores` (
  `id_score` INT NOT NULL,
  `fk_game_Sco` INT NOT NULL,
  `fk_player_Sco` INT NOT NULL,
  `scoreVal` DOUBLE NULL,
  PRIMARY KEY (`id_score`),
  INDEX `fkGame_idx` (`fk_game_Sco` ASC),
  INDEX `fkPlayer_idx` (`fk_player_Sco` ASC),
  CONSTRAINT `fk_game_Sco`
    FOREIGN KEY (`fk_game_Sco`)
    REFERENCES `plantgamedb`.`GameInstance` (`idGameInstance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_Sco`
    FOREIGN KEY (`fk_player_Sco`)
    REFERENCES `plantgamedb`.`Player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`PlayerPlants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`PlayerPlants` (
  `id_playerResource` INT NOT NULL AUTO_INCREMENT,
  `fk_player_Plpl` INT NOT NULL,
  `fk_plant_Plpl` INT NOT NULL,
  PRIMARY KEY (`id_playerResource`),
  INDEX `fkPlayer_idx` (`fk_player_Plpl` ASC),
  INDEX `fkPlant_idx` (`fk_plant_Plpl` ASC),
  CONSTRAINT `fk_player_Plpl`
    FOREIGN KEY (`fk_player_Plpl`)
    REFERENCES `plantgamedb`.`Player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plant_Plpl`
    FOREIGN KEY (`fk_plant_Plpl`)
    REFERENCES `plantgamedb`.`PlantList` (`id_Plant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`MasterList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`MasterList` (
  `id_masterList` INT NOT NULL AUTO_INCREMENT,
  `fk_game_Mas` INT NOT NULL,
  `fk_player_Mas` INT NOT NULL,
  PRIMARY KEY (`id_masterList`),
  INDEX `fkGame_idx` (`fk_game_Mas` ASC),
  INDEX `fkPlayer_idx` (`fk_player_Mas` ASC),
  CONSTRAINT `fk_game_Mas`
    FOREIGN KEY (`fk_game_Mas`)
    REFERENCES `plantgamedb`.`GameInstance` (`idGameInstance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_Mas`
    FOREIGN KEY (`fk_player_Mas`)
    REFERENCES `plantgamedb`.`Player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantgamedb`.`PlantResActive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantgamedb`.`PlantResActive` (
  `id_plantResActive` INT NOT NULL AUTO_INCREMENT,
  `fk_plant_PlRA` INT NOT NULL,
  `fk_resource_PlRA` INT NOT NULL,
  `resQuantity` DECIMAL(4,1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_plantResActive`),
  UNIQUE INDEX `idPlantResActive_UNIQUE` (`id_plantResActive` ASC),
  INDEX `fkResource_idx` (`fk_resource_PlRA` ASC),
  INDEX `fkPlant_idx` (`fk_plant_PlRA` ASC),
  CONSTRAINT `fk_resource_PlRA`
    FOREIGN KEY (`fk_resource_PlRA`)
    REFERENCES `plantgamedb`.`PlantResReference` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plant_PlRA`
    FOREIGN KEY (`fk_plant_PlRA`)
    REFERENCES `plantgamedb`.`PlantList` (`id_Plant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
